import { ArrowUpRight, BookOpenCheck, Clock3, FileText, Sparkles, Brain, CircleCheck, MoreHorizontal } from "lucide-react";

const docs = [
  { title: "Neural Retrieval Systems.pdf", meta: "42 pages · Research", status: "Ready", pct: 72 },
  { title: "Arabic OCR Benchmark.pdf", meta: "18 pages · University", status: "Ready", pct: 31 },
  { title: "Q3 Market Analysis.pptx", meta: "27 slides · Work", status: "Processing", pct: 0 }
];
export default function DashboardPage() {
  return <div className="mx-auto max-w-[1500px] p-6 lg:p-8"><div className="mb-7 flex items-end justify-between"><div><p className="text-sm text-ink/50">Wednesday, September 16</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.03em]">Good afternoon.</h1><p className="mt-1 text-sm text-ink/55">Pick up where you left off, or turn a new document into knowledge.</p></div><button className="hidden items-center gap-2 text-sm text-ink/55 hover:text-ink md:flex">View activity <ArrowUpRight size={15}/></button></div>
  <section className="grid gap-4 lg:grid-cols-[1.5fr_.75fr_.75fr]"><div className="surface relative overflow-hidden p-6"><div className="absolute end-5 top-5 grid h-11 w-11 place-items-center rounded-2xl bg-accent/10 text-accent"><Sparkles size={21}/></div><p className="text-xs font-semibold uppercase tracking-[.18em] text-ink/40">Continue reading</p><h2 className="mt-8 max-w-lg text-xl font-semibold">Neural Retrieval Systems</h2><p className="mt-2 max-w-xl text-sm leading-6 text-ink/55">You were on page 31, exploring hybrid ranking and reranking strategies.</p><div className="mt-5 h-1.5 max-w-md overflow-hidden rounded-full bg-muted"><div className="h-full w-[72%] bg-accent"/></div><button className="mt-5 rounded-xl bg-ink px-4 py-2 text-sm font-medium text-panel">Continue on page 31</button></div><Metric icon={FileText} label="Storage" value="428 MB" note="of 1 GB"/><Metric icon={Brain} label="Due today" value="24 cards" note="3 decks"/></section>
  <section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Recent documents</h2><button className="text-sm text-ink/50 hover:text-ink">See all</button></div><div className="surface overflow-hidden"><div className="grid grid-cols-[1fr_190px_130px_44px] border-b bg-muted/35 px-4 py-2.5 text-[11px] font-semibold uppercase tracking-wider text-ink/40"><span>Name</span><span>Workspace</span><span>Status</span><span/></div>{docs.map((doc, i)=><div key={doc.title} className="grid grid-cols-[1fr_190px_130px_44px] items-center border-b px-4 py-3.5 last:border-0 hover:bg-muted/30"><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-muted"><FileText size={17}/></div><div className="min-w-0"><p className="truncate text-sm font-medium">{doc.title}</p><p className="text-xs text-ink/45">{doc.meta}</p></div></div><span className="text-sm text-ink/55">{i===2?"Work":"Research"}</span><span className="flex items-center gap-1.5 text-xs text-ink/60">{doc.status === "Ready" ? <CircleCheck size={14} className="text-emerald-500"/> : <Clock3 size={14} className="text-amber-500"/>}{doc.status}</span><button className="grid h-8 w-8 place-items-center rounded-lg hover:bg-muted"><MoreHorizontal size={16}/></button></div>)}</div></section>
  <section className="mt-8 grid gap-4 md:grid-cols-3"><Quick icon={Sparkles} title="Ask across your workspace" copy="Search and reason across documents with source-linked answers."/><Quick icon={BookOpenCheck} title="Generate a study set" copy="Turn selected pages into flashcards and a cited quiz."/><Quick icon={Brain} title="Compare documents" copy="Find differences, contradictions, shared metrics, and timelines."/></section></div>;
}
function Metric({icon:Icon,label,value,note}:{icon:typeof FileText,label:string,value:string,note:string}){return <div className="surface p-5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-muted"><Icon size={17}/></div><p className="mt-7 text-xs text-ink/45">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="text-xs text-ink/40">{note}</p></div>}
function Quick({icon:Icon,title,copy}:{icon:typeof FileText,title:string,copy:string}){return <button className="surface group p-5 text-left transition hover:-translate-y-0.5 hover:shadow-soft"><Icon size={19} className="text-accent"/><h3 className="mt-5 font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-ink/50">{copy}</p><ArrowUpRight className="mt-4 text-ink/30 transition group-hover:text-ink" size={16}/></button>}
