"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight, Minus, Plus, Search } from "lucide-react";

export function PdfViewer({ fileUrl, initialPage = 1 }: { fileUrl?: string; initialPage?: number }) {
  const [page, setPage] = useState(initialPage);
  const [zoom, setZoom] = useState(100);
  return <div className="flex h-full min-h-0 flex-col bg-muted/35"><div className="flex h-12 shrink-0 items-center justify-between border-b bg-panel px-3"><div className="flex items-center gap-1"><button className="rounded-lg p-2 hover:bg-muted" onClick={()=>setPage(Math.max(1,page-1))}><ChevronLeft size={15}/></button><span className="min-w-20 text-center text-xs">Page {page}</span><button className="rounded-lg p-2 hover:bg-muted" onClick={()=>setPage(page+1)}><ChevronRight size={15}/></button></div><div className="flex items-center gap-1"><button className="rounded-lg p-2 hover:bg-muted"><Search size={15}/></button><button className="rounded-lg p-2 hover:bg-muted" onClick={()=>setZoom(Math.max(60,zoom-10))}><Minus size={15}/></button><span className="w-12 text-center text-xs">{zoom}%</span><button className="rounded-lg p-2 hover:bg-muted" onClick={()=>setZoom(Math.min(180,zoom+10))}><Plus size={15}/></button></div></div><div className="min-h-0 flex-1 overflow-auto p-6"><div className="mx-auto aspect-[1/1.414] w-full max-w-[820px] origin-top bg-white p-[7%] text-slate-900 shadow-soft" style={{transform:`scale(${zoom/100})`}}><p className="text-xs uppercase tracking-widest text-slate-400">Page {page}</p><h1 className="mt-10 text-3xl font-semibold tracking-tight">Hybrid Retrieval Systems</h1><p className="mt-7 text-sm leading-7">DocMind renders the production PDF through a signed, permission-checked file URL. Citation clicks update the reader page and highlight the associated source region when bounding-box metadata is available.</p><div className="mt-7 rounded bg-blue-50 p-4 text-sm leading-6 outline outline-2 outline-blue-200">This preview block represents a citation-linked source excerpt. The reader route keeps page and chunk IDs in the URL so citations remain deep-linkable and shareable within authorized workspaces.</div>{fileUrl && <p className="mt-8 text-xs text-slate-400">Signed source loaded securely.</p>}</div></div></div>;
}
